matrix:
  include:
  - language: python
    services: postgresql
    python:
    - '3.3'
    - '3.5'
    - '3.6'
    before_script:
    - cd python
    before_install:
    - export PIP_USE_MIRRORS=true
    install:
    - easy_install distribute
    - pip install -r requirements.txt
    script:
    # change later
    - python root_route.py runserver"
