matrix:
  include:
  - language: c
    compiler:
    - gcc
    before_script:
    - cd c
    script:
    - make
  - language: python
    services: postgresql
    python:
    - '3.3'
    - '3.5'
    - '3.6'
    before_script:
    - cd python
    before_install:
    - export PIP_USE_MIRRORS=true
    install:
    - easy_install distribute
    - pip install -r requirements.txt
    before_script:
    - psql -c "CREATE DATABASE jobsdb;" -U bklo
    script:
    # change later
    - python root_route.py runserver"
